
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('@prisma/client/runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.19.3
 * Query Engine version: c2990dca591cba766e3b7ef5d9e8a84796e47ab7
 */
Prisma.prismaVersion = {
  client: "6.19.3",
  engine: "c2990dca591cba766e3b7ef5d9e8a84796e47ab7"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.UserScalarFieldEnum = {
  id: 'id',
  email: 'email',
  name: 'name',
  passwordHash: 'passwordHash',
  role: 'role',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.BrandScalarFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug',
  active: 'active',
  currency: 'currency',
  taxRate: 'taxRate',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ApiCredentialScalarFieldEnum = {
  id: 'id',
  brandId: 'brandId',
  provider: 'provider',
  keyEncrypted: 'keyEncrypted',
  meta: 'meta',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SettingScalarFieldEnum = {
  id: 'id',
  brandId: 'brandId',
  key: 'key',
  value: 'value',
  updatedAt: 'updatedAt'
};

exports.Prisma.AuditLogScalarFieldEnum = {
  id: 'id',
  brandId: 'brandId',
  actor: 'actor',
  action: 'action',
  entity: 'entity',
  entityId: 'entityId',
  payload: 'payload',
  autonomyLevel: 'autonomyLevel',
  createdAt: 'createdAt'
};

exports.Prisma.ResearchRunScalarFieldEnum = {
  id: 'id',
  brandId: 'brandId',
  source: 'source',
  status: 'status',
  query: 'query',
  createdAt: 'createdAt',
  finishedAt: 'finishedAt'
};

exports.Prisma.ResearchResultScalarFieldEnum = {
  id: 'id',
  runId: 'runId',
  title: 'title',
  url: 'url',
  demandScore: 'demandScore',
  competitionScore: 'competitionScore',
  salesPotential: 'salesPotential',
  profitScore: 'profitScore',
  raw: 'raw',
  createdAt: 'createdAt'
};

exports.Prisma.TrendScalarFieldEnum = {
  id: 'id',
  brandId: 'brandId',
  week: 'week',
  niche: 'niche',
  theme: 'theme',
  score: 'score',
  source: 'source',
  createdAt: 'createdAt'
};

exports.Prisma.OpportunityScalarFieldEnum = {
  id: 'id',
  brandId: 'brandId',
  title: 'title',
  niche: 'niche',
  kind: 'kind',
  sourceSignals: 'sourceSignals',
  opportunityScore: 'opportunityScore',
  validationScore: 'validationScore',
  validationSignals: 'validationSignals',
  seasonalityScore: 'seasonalityScore',
  priorityScore: 'priorityScore',
  aiRationale: 'aiRationale',
  status: 'status',
  eventDate: 'eventDate',
  week: 'week',
  designId: 'designId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CommercialEventScalarFieldEnum = {
  id: 'id',
  brandId: 'brandId',
  name: 'name',
  category: 'category',
  eventDate: 'eventDate',
  prepLeadDays: 'prepLeadDays',
  trendPotential: 'trendPotential',
  salesPotential: 'salesPotential',
  eventScore: 'eventScore',
  linkedOpportunityId: 'linkedOpportunityId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CompetitorScalarFieldEnum = {
  id: 'id',
  brandId: 'brandId',
  name: 'name',
  url: 'url',
  metaPageId: 'metaPageId',
  createdAt: 'createdAt'
};

exports.Prisma.CompetitorProductScalarFieldEnum = {
  id: 'id',
  competitorId: 'competitorId',
  title: 'title',
  price: 'price',
  currency: 'currency',
  url: 'url',
  seenAt: 'seenAt'
};

exports.Prisma.CompetitorAdScalarFieldEnum = {
  id: 'id',
  competitorId: 'competitorId',
  platform: 'platform',
  creativeUrl: 'creativeUrl',
  copy: 'copy',
  seenAt: 'seenAt'
};

exports.Prisma.DesignBriefScalarFieldEnum = {
  id: 'id',
  brandId: 'brandId',
  summary: 'summary',
  targetAudience: 'targetAudience',
  trendRefs: 'trendRefs',
  createdAt: 'createdAt'
};

exports.Prisma.DesignScalarFieldEnum = {
  id: 'id',
  brandId: 'brandId',
  briefId: 'briefId',
  prompt: 'prompt',
  svgUrl: 'svgUrl',
  pngUrl: 'pngUrl',
  transparentUrl: 'transparentUrl',
  printReadyUrl: 'printReadyUrl',
  scores: 'scores',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.MockupScalarFieldEnum = {
  id: 'id',
  brandId: 'brandId',
  designId: 'designId',
  type: 'type',
  url: 'url',
  createdAt: 'createdAt'
};

exports.Prisma.VideoScalarFieldEnum = {
  id: 'id',
  brandId: 'brandId',
  productId: 'productId',
  type: 'type',
  url: 'url',
  status: 'status',
  createdAt: 'createdAt'
};

exports.Prisma.ProductScalarFieldEnum = {
  id: 'id',
  brandId: 'brandId',
  title: 'title',
  description: 'description',
  status: 'status',
  designId: 'designId',
  shopifyId: 'shopifyId',
  printifyProductId: 'printifyProductId',
  printifyShopId: 'printifyShopId',
  mockups: 'mockups',
  cost: 'cost',
  price: 'price',
  pageViews: 'pageViews',
  cartAdds: 'cartAdds',
  wishlistAdds: 'wishlistAdds',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ProductConversionScalarFieldEnum = {
  id: 'id',
  brandId: 'brandId',
  productId: 'productId',
  week: 'week',
  pageViews: 'pageViews',
  cartAdds: 'cartAdds',
  wishlistAdds: 'wishlistAdds',
  behaviorScore: 'behaviorScore',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ProductLifecycleEventScalarFieldEnum = {
  id: 'id',
  productId: 'productId',
  from: 'from',
  to: 'to',
  reason: 'reason',
  createdAt: 'createdAt'
};

exports.Prisma.ProductIntelligenceScalarFieldEnum = {
  id: 'id',
  brandId: 'brandId',
  productId: 'productId',
  status: 'status',
  seoTitle: 'seoTitle',
  seoDescription: 'seoDescription',
  seoKeywords: 'seoKeywords',
  handle: 'handle',
  description: 'description',
  shortDescription: 'shortDescription',
  story: 'story',
  faq: 'faq',
  ads: 'ads',
  salesAngles: 'salesAngles',
  audience: 'audience',
  ugc: 'ugc',
  campaignPrep: 'campaignPrep',
  score: 'score',
  scoreTotal: 'scoreTotal',
  demandScore: 'demandScore',
  previousDemandScore: 'previousDemandScore',
  aiRationale: 'aiRationale',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ShopifyCollectionScalarFieldEnum = {
  id: 'id',
  brandId: 'brandId',
  shopifyId: 'shopifyId',
  title: 'title',
  createdAt: 'createdAt'
};

exports.Prisma.ShopifyHealthCheckScalarFieldEnum = {
  id: 'id',
  brandId: 'brandId',
  type: 'type',
  passed: 'passed',
  detail: 'detail',
  createdAt: 'createdAt'
};

exports.Prisma.AdCampaignScalarFieldEnum = {
  id: 'id',
  brandId: 'brandId',
  metaId: 'metaId',
  name: 'name',
  status: 'status',
  objective: 'objective',
  dailyBudget: 'dailyBudget',
  productId: 'productId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.AdSetScalarFieldEnum = {
  id: 'id',
  campaignId: 'campaignId',
  metaId: 'metaId',
  name: 'name',
  status: 'status',
  budget: 'budget',
  createdAt: 'createdAt'
};

exports.Prisma.AdScalarFieldEnum = {
  id: 'id',
  adsetId: 'adsetId',
  metaId: 'metaId',
  name: 'name',
  status: 'status',
  creativeUrl: 'creativeUrl',
  createdAt: 'createdAt'
};

exports.Prisma.AdMetricScalarFieldEnum = {
  id: 'id',
  brandId: 'brandId',
  level: 'level',
  refId: 'refId',
  date: 'date',
  spend: 'spend',
  roas: 'roas',
  cpa: 'cpa',
  cpc: 'cpc',
  ctr: 'ctr',
  impressions: 'impressions',
  clicks: 'clicks',
  conversions: 'conversions',
  createdAt: 'createdAt'
};

exports.Prisma.CreativeTestScalarFieldEnum = {
  id: 'id',
  brandId: 'brandId',
  hypothesis: 'hypothesis',
  variants: 'variants',
  status: 'status',
  winner: 'winner',
  createdAt: 'createdAt'
};

exports.Prisma.SupplierScalarFieldEnum = {
  id: 'id',
  brandId: 'brandId',
  company: 'company',
  email: 'email',
  phone: 'phone',
  website: 'website',
  notes: 'notes',
  verified: 'verified',
  moq: 'moq',
  unitCost: 'unitCost',
  costCurrency: 'costCurrency',
  deliveryDays: 'deliveryDays',
  supplierScore: 'supplierScore',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.EmailMessageScalarFieldEnum = {
  id: 'id',
  brandId: 'brandId',
  supplierId: 'supplierId',
  direction: 'direction',
  subject: 'subject',
  body: 'body',
  status: 'status',
  sentAt: 'sentAt',
  createdAt: 'createdAt'
};

exports.Prisma.OrderScalarFieldEnum = {
  id: 'id',
  brandId: 'brandId',
  shopifyId: 'shopifyId',
  total: 'total',
  currency: 'currency',
  financialStatus: 'financialStatus',
  createdAt: 'createdAt'
};

exports.Prisma.FinanceSnapshotScalarFieldEnum = {
  id: 'id',
  brandId: 'brandId',
  date: 'date',
  revenue: 'revenue',
  adSpend: 'adSpend',
  cogs: 'cogs',
  shipping: 'shipping',
  commission: 'commission',
  opex: 'opex',
  grossProfit: 'grossProfit',
  netProfit: 'netProfit',
  taxEstimate: 'taxEstimate',
  orders: 'orders',
  aov: 'aov',
  createdAt: 'createdAt'
};

exports.Prisma.OperationScoreScalarFieldEnum = {
  id: 'id',
  brandId: 'brandId',
  date: 'date',
  adScore: 'adScore',
  seoScore: 'seoScore',
  profitScore: 'profitScore',
  qualityScore: 'qualityScore',
  trendScore: 'trendScore',
  overall: 'overall',
  createdAt: 'createdAt'
};

exports.Prisma.AIReportScalarFieldEnum = {
  id: 'id',
  brandId: 'brandId',
  type: 'type',
  period: 'period',
  summary: 'summary',
  insights: 'insights',
  recommendations: 'recommendations',
  createdAt: 'createdAt'
};

exports.Prisma.AIDecisionScalarFieldEnum = {
  id: 'id',
  brandId: 'brandId',
  reportId: 'reportId',
  title: 'title',
  rationale: 'rationale',
  action: 'action',
  params: 'params',
  status: 'status',
  confidence: 'confidence',
  expectedImpact: 'expectedImpact',
  riskLevel: 'riskLevel',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.TaskScalarFieldEnum = {
  id: 'id',
  brandId: 'brandId',
  title: 'title',
  description: 'description',
  type: 'type',
  status: 'status',
  priority: 'priority',
  dueAt: 'dueAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.JobScalarFieldEnum = {
  id: 'id',
  brandId: 'brandId',
  queue: 'queue',
  name: 'name',
  status: 'status',
  payload: 'payload',
  result: 'result',
  error: 'error',
  createdAt: 'createdAt',
  finishedAt: 'finishedAt'
};

exports.Prisma.SpendLimitScalarFieldEnum = {
  id: 'id',
  brandId: 'brandId',
  period: 'period',
  amount: 'amount',
  active: 'active',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.BackupScalarFieldEnum = {
  id: 'id',
  brandId: 'brandId',
  type: 'type',
  location: 'location',
  sizeBytes: 'sizeBytes',
  createdAt: 'createdAt'
};

exports.Prisma.UsageLogScalarFieldEnum = {
  id: 'id',
  brandId: 'brandId',
  provider: 'provider',
  model: 'model',
  tokensIn: 'tokensIn',
  tokensOut: 'tokensOut',
  cost: 'cost',
  createdAt: 'createdAt'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.NullableJsonNullValueInput = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull
};

exports.Prisma.JsonNullValueInput = {
  JsonNull: Prisma.JsonNull
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};

exports.Prisma.JsonNullValueFilter = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull,
  AnyNull: Prisma.AnyNull
};
exports.Role = exports.$Enums.Role = {
  OWNER: 'OWNER',
  ADMIN: 'ADMIN'
};

exports.Provider = exports.$Enums.Provider = {
  OPENAI: 'OPENAI',
  FAL: 'FAL',
  ANTHROPIC: 'ANTHROPIC',
  SHOPIFY: 'SHOPIFY',
  META: 'META',
  SMTP: 'SMTP',
  ETSY: 'ETSY',
  PINTEREST: 'PINTEREST',
  PRINTIFY: 'PRINTIFY'
};

exports.Source = exports.$Enums.Source = {
  TIKTOK: 'TIKTOK',
  PINTEREST: 'PINTEREST',
  ETSY: 'ETSY',
  AMAZON: 'AMAZON',
  REDDIT: 'REDDIT',
  HACKERNEWS: 'HACKERNEWS',
  TRENDYOL: 'TRENDYOL',
  HEPSIBURADA: 'HEPSIBURADA',
  SIKAYETVAR: 'SIKAYETVAR',
  INSTAGRAM: 'INSTAGRAM',
  GOOGLE_TRENDS: 'GOOGLE_TRENDS'
};

exports.JobStatus = exports.$Enums.JobStatus = {
  QUEUED: 'QUEUED',
  RUNNING: 'RUNNING',
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED'
};

exports.OpportunityKind = exports.$Enums.OpportunityKind = {
  TREND: 'TREND',
  PROBLEM: 'PROBLEM',
  EVENT: 'EVENT'
};

exports.OpportunityStatus = exports.$Enums.OpportunityStatus = {
  NEW: 'NEW',
  SCORED: 'SCORED',
  VALIDATED: 'VALIDATED',
  REJECTED: 'REJECTED',
  PURSUED: 'PURSUED'
};

exports.EventCategory = exports.$Enums.EventCategory = {
  SPOR: 'SPOR',
  ALISVERIS: 'ALISVERIS',
  KUTLAMA: 'KUTLAMA',
  MEVSIM: 'MEVSIM'
};

exports.AssetStatus = exports.$Enums.AssetStatus = {
  DRAFT: 'DRAFT',
  GENERATING: 'GENERATING',
  READY: 'READY',
  FAILED: 'FAILED',
  PUBLISHED: 'PUBLISHED'
};

exports.MockupType = exports.$Enums.MockupType = {
  TSHIRT: 'TSHIRT',
  HOODIE: 'HOODIE',
  SWEATSHIRT: 'SWEATSHIRT',
  OVERSIZE: 'OVERSIZE',
  MODEL_FRONT: 'MODEL_FRONT',
  MODEL_ANGLE: 'MODEL_ANGLE',
  MODEL_FRONT_W: 'MODEL_FRONT_W',
  MODEL_ANGLE_W: 'MODEL_ANGLE_W'
};

exports.VideoType = exports.$Enums.VideoType = {
  TIKTOK: 'TIKTOK',
  REEL: 'REEL',
  STORY: 'STORY',
  UGC: 'UGC'
};

exports.LifecycleStatus = exports.$Enums.LifecycleStatus = {
  NEW: 'NEW',
  TEST: 'TEST',
  WINNER: 'WINNER',
  SCALING: 'SCALING',
  DECLINING: 'DECLINING',
  CLOSED: 'CLOSED'
};

exports.MailDir = exports.$Enums.MailDir = {
  INBOUND: 'INBOUND',
  OUTBOUND: 'OUTBOUND'
};

exports.MailStatus = exports.$Enums.MailStatus = {
  DRAFT: 'DRAFT',
  SENT: 'SENT',
  FAILED: 'FAILED'
};

exports.ReportType = exports.$Enums.ReportType = {
  WEEKLY: 'WEEKLY',
  CEO: 'CEO',
  FINANCE: 'FINANCE'
};

exports.DecisionAction = exports.$Enums.DecisionAction = {
  CONVERT_OPPORTUNITY: 'CONVERT_OPPORTUNITY',
  GENERATE_INTELLIGENCE: 'GENERATE_INTELLIGENCE',
  PREP_EVENT_DESIGN: 'PREP_EVENT_DESIGN',
  ADJUST_AD_BUDGET: 'ADJUST_AD_BUDGET',
  PAUSE_CAMPAIGN: 'PAUSE_CAMPAIGN',
  CONTACT_SUPPLIER: 'CONTACT_SUPPLIER',
  EXIT_NICHE: 'EXIT_NICHE',
  APPLY_SUPPLIER_COST: 'APPLY_SUPPLIER_COST',
  CREATE_AD_DRAFT: 'CREATE_AD_DRAFT',
  GENERIC: 'GENERIC'
};

exports.DecisionStatus = exports.$Enums.DecisionStatus = {
  PENDING: 'PENDING',
  APPLIED: 'APPLIED',
  DISMISSED: 'DISMISSED'
};

exports.TaskType = exports.$Enums.TaskType = {
  API_INPUT: 'API_INPUT',
  APPROVE_DESIGN: 'APPROVE_DESIGN',
  APPROVE_AD: 'APPROVE_AD',
  GENERIC: 'GENERIC'
};

exports.TaskStatus = exports.$Enums.TaskStatus = {
  OPEN: 'OPEN',
  IN_PROGRESS: 'IN_PROGRESS',
  DONE: 'DONE',
  CANCELLED: 'CANCELLED'
};

exports.LimitPeriod = exports.$Enums.LimitPeriod = {
  DAILY: 'DAILY',
  WEEKLY: 'WEEKLY',
  MONTHLY: 'MONTHLY'
};

exports.BackupType = exports.$Enums.BackupType = {
  DATABASE: 'DATABASE',
  WORKFLOW: 'WORKFLOW',
  ASSETS: 'ASSETS'
};

exports.Prisma.ModelName = {
  User: 'User',
  Brand: 'Brand',
  ApiCredential: 'ApiCredential',
  Setting: 'Setting',
  AuditLog: 'AuditLog',
  ResearchRun: 'ResearchRun',
  ResearchResult: 'ResearchResult',
  Trend: 'Trend',
  Opportunity: 'Opportunity',
  CommercialEvent: 'CommercialEvent',
  Competitor: 'Competitor',
  CompetitorProduct: 'CompetitorProduct',
  CompetitorAd: 'CompetitorAd',
  DesignBrief: 'DesignBrief',
  Design: 'Design',
  Mockup: 'Mockup',
  Video: 'Video',
  Product: 'Product',
  ProductConversion: 'ProductConversion',
  ProductLifecycleEvent: 'ProductLifecycleEvent',
  ProductIntelligence: 'ProductIntelligence',
  ShopifyCollection: 'ShopifyCollection',
  ShopifyHealthCheck: 'ShopifyHealthCheck',
  AdCampaign: 'AdCampaign',
  AdSet: 'AdSet',
  Ad: 'Ad',
  AdMetric: 'AdMetric',
  CreativeTest: 'CreativeTest',
  Supplier: 'Supplier',
  EmailMessage: 'EmailMessage',
  Order: 'Order',
  FinanceSnapshot: 'FinanceSnapshot',
  OperationScore: 'OperationScore',
  AIReport: 'AIReport',
  AIDecision: 'AIDecision',
  Task: 'Task',
  Job: 'Job',
  SpendLimit: 'SpendLimit',
  Backup: 'Backup',
  UsageLog: 'UsageLog'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
